### ISSUE TITLE
"*** stack smashing detected ***: terminated" message in output

### ISSUE THREAD

**Issue by VitorGoatman** [escondida/ddate#1]
`ddate` seems to execute just fine, but there's an added error message in the output:

![image](https://user-images.githubusercontent.com/24948560/79025886-739c0080-7b5d-11ea-9413-e81d1b800e71.png)

I'm using ZSH as the main shell, but the same issue happens when running it with bash

![image](https://user-images.githubusercontent.com/24948560/79026185-603d6500-7b5e-11ea-96fe-ff86d449c3d9.png)
 
The error message isn't there when I run it with some arguments like so 
![image](https://user-images.githubusercontent.com/24948560/79026444-405a7100-7b5f-11ea-9204-404e92a97b36.png)

**EDIT:** I played around with the arguments, it seems `%W` is causing it.
![image](https://user-images.githubusercontent.com/24948560/79028207-8286b100-7b65-11ea-8163-c437f5f79b0d.png)

**Comment by escondida** [comment]
Weird! I should have some time to look at this in the next couple of days. Thanks for the report!

**Comment by escondida** [comment]
VitorGoatman, I can't seem to reproduce this. What compiler and what CFLAGS and LDFLAGS did you use? Also, what platform are you on?


For my part, I've tried it with both clang and gcc on Linux.

**Comment by escondida** [comment]
This should be fixed by commit 16dfec863bcb54580e06c50862325b9af26e3a7d . I'm still not sure why one weekday string was causing problems for you and the other wasn't, but...eh.
